import tw, { theme } from './macro'

// https://tailwindcss.com/docs/scroll-padding
theme`scrollPadding`

tw`scroll-p-0`
tw`scroll-px-0`
tw`scroll-py-0`
tw`scroll-pt-0`
tw`scroll-pr-0`
tw`scroll-pb-0`
tw`scroll-pl-0`
tw`scroll-p-px`
tw`scroll-px-px`
tw`scroll-py-px`
tw`scroll-pt-px`
tw`scroll-pr-px`
tw`scroll-pb-px`
tw`scroll-pl-px`
tw`scroll-p-0`
tw`scroll-px-0`
tw`scroll-py-0`
tw`scroll-pt-0`
tw`scroll-pr-0`
tw`scroll-pb-0`
tw`scroll-pl-0`
tw`scroll-p-1`
tw`scroll-px-1`
tw`scroll-py-1`
tw`scroll-pt-1`
tw`scroll-pr-1`
tw`scroll-pb-1`
tw`scroll-pl-1`
tw`scroll-p-1`
tw`scroll-px-1`
tw`scroll-py-1`
tw`scroll-pt-1`
tw`scroll-pr-1`
tw`scroll-pb-1`
tw`scroll-pl-1`
tw`scroll-p-2`
tw`scroll-px-2`
tw`scroll-py-2`
tw`scroll-pt-2`
tw`scroll-pr-2`
tw`scroll-pb-2`
tw`scroll-pl-2`
tw`scroll-p-2`
tw`scroll-px-2`
tw`scroll-py-2`
tw`scroll-pt-2`
tw`scroll-pr-2`
tw`scroll-pb-2`
tw`scroll-pl-2`
tw`scroll-p-3`
tw`scroll-px-3`
tw`scroll-py-3`
tw`scroll-pt-3`
tw`scroll-pr-3`
tw`scroll-pb-3`
tw`scroll-pl-3`
tw`scroll-p-3`
tw`scroll-px-3`
tw`scroll-py-3`
tw`scroll-pt-3`
tw`scroll-pr-3`
tw`scroll-pb-3`
tw`scroll-pl-3`
tw`scroll-p-4`
tw`scroll-px-4`
tw`scroll-py-4`
tw`scroll-pt-4`
tw`scroll-pr-4`
tw`scroll-pb-4`
tw`scroll-pl-4`
tw`scroll-p-5`
tw`scroll-px-5`
tw`scroll-py-5`
tw`scroll-pt-5`
tw`scroll-pr-5`
tw`scroll-pb-5`
tw`scroll-pl-5`
tw`scroll-p-6`
tw`scroll-px-6`
tw`scroll-py-6`
tw`scroll-pt-6`
tw`scroll-pr-6`
tw`scroll-pb-6`
tw`scroll-pl-6`
tw`scroll-p-7`
tw`scroll-px-7`
tw`scroll-py-7`
tw`scroll-pt-7`
tw`scroll-pr-7`
tw`scroll-pb-7`
tw`scroll-pl-7`
tw`scroll-p-8`
tw`scroll-px-8`
tw`scroll-py-8`
tw`scroll-pt-8`
tw`scroll-pr-8`
tw`scroll-pb-8`
tw`scroll-pl-8`
tw`scroll-p-9`
tw`scroll-px-9`
tw`scroll-py-9`
tw`scroll-pt-9`
tw`scroll-pr-9`
tw`scroll-pb-9`
tw`scroll-pl-9`
tw`scroll-p-10`
tw`scroll-px-10`
tw`scroll-py-10`
tw`scroll-pt-10`
tw`scroll-pr-10`
tw`scroll-pb-10`
tw`scroll-pl-10`
tw`scroll-p-11`
tw`scroll-px-11`
tw`scroll-py-11`
tw`scroll-pt-11`
tw`scroll-pr-11`
tw`scroll-pb-11`
tw`scroll-pl-11`
tw`scroll-p-12`
tw`scroll-px-12`
tw`scroll-py-12`
tw`scroll-pt-12`
tw`scroll-pr-12`
tw`scroll-pb-12`
tw`scroll-pl-12`
tw`scroll-p-14`
tw`scroll-px-14`
tw`scroll-py-14`
tw`scroll-pt-14`
tw`scroll-pr-14`
tw`scroll-pb-14`
tw`scroll-pl-14`
tw`scroll-p-16`
tw`scroll-px-16`
tw`scroll-py-16`
tw`scroll-pt-16`
tw`scroll-pr-16`
tw`scroll-pb-16`
tw`scroll-pl-16`
tw`scroll-p-20`
tw`scroll-px-20`
tw`scroll-py-20`
tw`scroll-pt-20`
tw`scroll-pr-20`
tw`scroll-pb-20`
tw`scroll-pl-20`
tw`scroll-p-24`
tw`scroll-px-24`
tw`scroll-py-24`
tw`scroll-pt-24`
tw`scroll-pr-24`
tw`scroll-pb-24`
tw`scroll-pl-24`
tw`scroll-p-28`
tw`scroll-px-28`
tw`scroll-py-28`
tw`scroll-pt-28`
tw`scroll-pr-28`
tw`scroll-pb-28`
tw`scroll-pl-28`
tw`scroll-p-32`
tw`scroll-px-32`
tw`scroll-py-32`
tw`scroll-pt-32`
tw`scroll-pr-32`
tw`scroll-pb-32`
tw`scroll-pl-32`
tw`scroll-p-36`
tw`scroll-px-36`
tw`scroll-py-36`
tw`scroll-pt-36`
tw`scroll-pr-36`
tw`scroll-pb-36`
tw`scroll-pl-36`
tw`scroll-p-40`
tw`scroll-px-40`
tw`scroll-py-40`
tw`scroll-pt-40`
tw`scroll-pr-40`
tw`scroll-pb-40`
tw`scroll-pl-40`
tw`scroll-p-44`
tw`scroll-px-44`
tw`scroll-py-44`
tw`scroll-pt-44`
tw`scroll-pr-44`
tw`scroll-pb-44`
tw`scroll-pl-44`
tw`scroll-p-48`
tw`scroll-px-48`
tw`scroll-py-48`
tw`scroll-pt-48`
tw`scroll-pr-48`
tw`scroll-pb-48`
tw`scroll-pl-48`
tw`scroll-p-52`
tw`scroll-px-52`
tw`scroll-py-52`
tw`scroll-pt-52`
tw`scroll-pr-52`
tw`scroll-pb-52`
tw`scroll-pl-52`
tw`scroll-p-56`
tw`scroll-px-56`
tw`scroll-py-56`
tw`scroll-pt-56`
tw`scroll-pr-56`
tw`scroll-pb-56`
tw`scroll-pl-56`
tw`scroll-p-60`
tw`scroll-px-60`
tw`scroll-py-60`
tw`scroll-pt-60`
tw`scroll-pr-60`
tw`scroll-pb-60`
tw`scroll-pl-60`
tw`scroll-p-64`
tw`scroll-px-64`
tw`scroll-py-64`
tw`scroll-pt-64`
tw`scroll-pr-64`
tw`scroll-pb-64`
tw`scroll-pl-64`
tw`scroll-p-72`
tw`scroll-px-72`
tw`scroll-py-72`
tw`scroll-pt-72`
tw`scroll-pr-72`
tw`scroll-pb-72`
tw`scroll-pl-72`
tw`scroll-p-80`
tw`scroll-px-80`
tw`scroll-py-80`
tw`scroll-pt-80`
tw`scroll-pr-80`
tw`scroll-pb-80`
tw`scroll-pl-80`
tw`scroll-p-96`
tw`scroll-px-96`
tw`scroll-py-96`
tw`scroll-pt-96`
tw`scroll-pr-96`
tw`scroll-pb-96`
tw`scroll-pl-96`

tw`scroll-p-[24rem]`
