import tw, { theme } from './macro'

// https://tailwindcss.com/docs/scroll-margin
theme`scrollMargin`

tw`scroll-m-0`
tw`scroll-mx-0`
tw`scroll-my-0`
tw`scroll-mt-0`
tw`scroll-mr-0`
tw`scroll-mb-0`
tw`scroll-ml-0`
tw`scroll-m-px`
tw`scroll-mx-px`
tw`scroll-my-px`
tw`scroll-mt-px`
tw`scroll-mr-px`
tw`scroll-mb-px`
tw`scroll-ml-px`
tw`scroll-m-0`
tw`scroll-mx-0`
tw`scroll-my-0`
tw`scroll-mt-0`
tw`scroll-mr-0`
tw`scroll-mb-0`
tw`scroll-ml-0`
tw`scroll-m-1`
tw`scroll-mx-1`
tw`scroll-my-1`
tw`scroll-mt-1`
tw`scroll-mr-1`
tw`scroll-mb-1`
tw`scroll-ml-1`
tw`scroll-m-1`
tw`scroll-mx-1`
tw`scroll-my-1`
tw`scroll-mt-1`
tw`scroll-mr-1`
tw`scroll-mb-1`
tw`scroll-ml-1`
tw`scroll-m-2`
tw`scroll-mx-2`
tw`scroll-my-2`
tw`scroll-mt-2`
tw`scroll-mr-2`
tw`scroll-mb-2`
tw`scroll-ml-2`
tw`scroll-m-2`
tw`scroll-mx-2`
tw`scroll-my-2`
tw`scroll-mt-2`
tw`scroll-mr-2`
tw`scroll-mb-2`
tw`scroll-ml-2`
tw`scroll-m-3`
tw`scroll-mx-3`
tw`scroll-my-3`
tw`scroll-mt-3`
tw`scroll-mr-3`
tw`scroll-mb-3`
tw`scroll-ml-3`
tw`scroll-m-3`
tw`scroll-mx-3`
tw`scroll-my-3`
tw`scroll-mt-3`
tw`scroll-mr-3`
tw`scroll-mb-3`
tw`scroll-ml-3`
tw`scroll-m-4`
tw`scroll-mx-4`
tw`scroll-my-4`
tw`scroll-mt-4`
tw`scroll-mr-4`
tw`scroll-mb-4`
tw`scroll-ml-4`
tw`scroll-m-5`
tw`scroll-mx-5`
tw`scroll-my-5`
tw`scroll-mt-5`
tw`scroll-mr-5`
tw`scroll-mb-5`
tw`scroll-ml-5`
tw`scroll-m-6`
tw`scroll-mx-6`
tw`scroll-my-6`
tw`scroll-mt-6`
tw`scroll-mr-6`
tw`scroll-mb-6`
tw`scroll-ml-6`
tw`scroll-m-7`
tw`scroll-mx-7`
tw`scroll-my-7`
tw`scroll-mt-7`
tw`scroll-mr-7`
tw`scroll-mb-7`
tw`scroll-ml-7`
tw`scroll-m-8`
tw`scroll-mx-8`
tw`scroll-my-8`
tw`scroll-mt-8`
tw`scroll-mr-8`
tw`scroll-mb-8`
tw`scroll-ml-8`
tw`scroll-m-9`
tw`scroll-mx-9`
tw`scroll-my-9`
tw`scroll-mt-9`
tw`scroll-mr-9`
tw`scroll-mb-9`
tw`scroll-ml-9`
tw`scroll-m-10`
tw`scroll-mx-10`
tw`scroll-my-10`
tw`scroll-mt-10`
tw`scroll-mr-10`
tw`scroll-mb-10`
tw`scroll-ml-10`
tw`scroll-m-11`
tw`scroll-mx-11`
tw`scroll-my-11`
tw`scroll-mt-11`
tw`scroll-mr-11`
tw`scroll-mb-11`
tw`scroll-ml-11`
tw`scroll-m-12`
tw`scroll-mx-12`
tw`scroll-my-12`
tw`scroll-mt-12`
tw`scroll-mr-12`
tw`scroll-mb-12`
tw`scroll-ml-12`
tw`scroll-m-14`
tw`scroll-mx-14`
tw`scroll-my-14`
tw`scroll-mt-14`
tw`scroll-mr-14`
tw`scroll-mb-14`
tw`scroll-ml-14`
tw`scroll-m-16`
tw`scroll-mx-16`
tw`scroll-my-16`
tw`scroll-mt-16`
tw`scroll-mr-16`
tw`scroll-mb-16`
tw`scroll-ml-16`
tw`scroll-m-20`
tw`scroll-mx-20`
tw`scroll-my-20`
tw`scroll-mt-20`
tw`scroll-mr-20`
tw`scroll-mb-20`
tw`scroll-ml-20`
tw`scroll-m-24`
tw`scroll-mx-24`
tw`scroll-my-24`
tw`scroll-mt-24`
tw`scroll-mr-24`
tw`scroll-mb-24`
tw`scroll-ml-24`
tw`scroll-m-28`
tw`scroll-mx-28`
tw`scroll-my-28`
tw`scroll-mt-28`
tw`scroll-mr-28`
tw`scroll-mb-28`
tw`scroll-ml-28`
tw`scroll-m-32`
tw`scroll-mx-32`
tw`scroll-my-32`
tw`scroll-mt-32`
tw`scroll-mr-32`
tw`scroll-mb-32`
tw`scroll-ml-32`
tw`scroll-m-36`
tw`scroll-mx-36`
tw`scroll-my-36`
tw`scroll-mt-36`
tw`scroll-mr-36`
tw`scroll-mb-36`
tw`scroll-ml-36`
tw`scroll-m-40`
tw`scroll-mx-40`
tw`scroll-my-40`
tw`scroll-mt-40`
tw`scroll-mr-40`
tw`scroll-mb-40`
tw`scroll-ml-40`
tw`scroll-m-44`
tw`scroll-mx-44`
tw`scroll-my-44`
tw`scroll-mt-44`
tw`scroll-mr-44`
tw`scroll-mb-44`
tw`scroll-ml-44`
tw`scroll-m-48`
tw`scroll-mx-48`
tw`scroll-my-48`
tw`scroll-mt-48`
tw`scroll-mr-48`
tw`scroll-mb-48`
tw`scroll-ml-48`
tw`scroll-m-52`
tw`scroll-mx-52`
tw`scroll-my-52`
tw`scroll-mt-52`
tw`scroll-mr-52`
tw`scroll-mb-52`
tw`scroll-ml-52`
tw`scroll-m-56`
tw`scroll-mx-56`
tw`scroll-my-56`
tw`scroll-mt-56`
tw`scroll-mr-56`
tw`scroll-mb-56`
tw`scroll-ml-56`
tw`scroll-m-60`
tw`scroll-mx-60`
tw`scroll-my-60`
tw`scroll-mt-60`
tw`scroll-mr-60`
tw`scroll-mb-60`
tw`scroll-ml-60`
tw`scroll-m-64`
tw`scroll-mx-64`
tw`scroll-my-64`
tw`scroll-mt-64`
tw`scroll-mr-64`
tw`scroll-mb-64`
tw`scroll-ml-64`
tw`scroll-m-72`
tw`scroll-mx-72`
tw`scroll-my-72`
tw`scroll-mt-72`
tw`scroll-mr-72`
tw`scroll-mb-72`
tw`scroll-ml-72`
tw`scroll-m-80`
tw`scroll-mx-80`
tw`scroll-my-80`
tw`scroll-mt-80`
tw`scroll-mr-80`
tw`scroll-mb-80`
tw`scroll-ml-80`
tw`scroll-m-96`
tw`scroll-mx-96`
tw`scroll-my-96`
tw`scroll-mt-96`
tw`scroll-mr-96`
tw`scroll-mb-96`
tw`scroll-ml-96`

tw`-scroll-m-96`
tw`-scroll-mx-96`
tw`-scroll-my-96`
tw`-scroll-mt-96`
tw`-scroll-mr-96`
tw`-scroll-mb-96`
tw`-scroll-ml-96`

tw`-scroll-m-[24rem]`
tw`scroll-m-[24rem]`
