// @ts-nocheck
import tw, { theme } from '../macro'

// https://tailwindcss.com/docs/border-spacing
theme`borderSpacing`

tw`border-spacing-0`
tw`border-spacing-x-0`
tw`border-spacing-y-0`
tw`border-spacing-px`
tw`border-spacing-x-px`
tw`border-spacing-y-px`
tw`border-spacing-0.5`
tw`border-spacing-x-0.5`
tw`border-spacing-y-0.5`
tw`border-spacing-1`
tw`border-spacing-x-1`
tw`border-spacing-y-1`
tw`border-spacing-1.5`
tw`border-spacing-x-1.5`
tw`border-spacing-y-1.5`
tw`border-spacing-2`
tw`border-spacing-x-2`
tw`border-spacing-y-2`
tw`border-spacing-2.5`
tw`border-spacing-x-2.5`
tw`border-spacing-y-2.5`
tw`border-spacing-3`
tw`border-spacing-x-3`
tw`border-spacing-y-3`
tw`border-spacing-3.5`
tw`border-spacing-x-3.5`
tw`border-spacing-y-3.5`
tw`border-spacing-4`
tw`border-spacing-x-4`
tw`border-spacing-y-4`
tw`border-spacing-5`
tw`border-spacing-x-5`
tw`border-spacing-y-5`
tw`border-spacing-6`
tw`border-spacing-x-6`
tw`border-spacing-y-6`
tw`border-spacing-7`
tw`border-spacing-x-7`
tw`border-spacing-y-7`
tw`border-spacing-8`
tw`border-spacing-x-8`
tw`border-spacing-y-8`
tw`border-spacing-9`
tw`border-spacing-x-9`
tw`border-spacing-y-9`
tw`border-spacing-10`
tw`border-spacing-x-10`
tw`border-spacing-y-10`
tw`border-spacing-11`
tw`border-spacing-x-11`
tw`border-spacing-y-11`
tw`border-spacing-12`
tw`border-spacing-x-12`
tw`border-spacing-y-12`
tw`border-spacing-14`
tw`border-spacing-x-14`
tw`border-spacing-y-14`
tw`border-spacing-16`
tw`border-spacing-x-16`
tw`border-spacing-y-16`
tw`border-spacing-20`
tw`border-spacing-x-20`
tw`border-spacing-y-20`
tw`border-spacing-24`
tw`border-spacing-x-24`
tw`border-spacing-y-24`
tw`border-spacing-28`
tw`border-spacing-x-28`
tw`border-spacing-y-28`
tw`border-spacing-32`
tw`border-spacing-x-32`
tw`border-spacing-y-32`
tw`border-spacing-36`
tw`border-spacing-x-36`
tw`border-spacing-y-36`
tw`border-spacing-40`
tw`border-spacing-x-40`
tw`border-spacing-y-40`
tw`border-spacing-44`
tw`border-spacing-x-44`
tw`border-spacing-y-44`
tw`border-spacing-48`
tw`border-spacing-x-48`
tw`border-spacing-y-48`
tw`border-spacing-52`
tw`border-spacing-x-52`
tw`border-spacing-y-52`
tw`border-spacing-56`
tw`border-spacing-x-56`
tw`border-spacing-y-56`
tw`border-spacing-60`
tw`border-spacing-x-60`
tw`border-spacing-y-60`
tw`border-spacing-64`
tw`border-spacing-x-64`
tw`border-spacing-y-64`
tw`border-spacing-72`
tw`border-spacing-x-72`
tw`border-spacing-y-72`
tw`border-spacing-80`
tw`border-spacing-x-80`
tw`border-spacing-y-80`
tw`border-spacing-96`
tw`border-spacing-x-96`
tw`border-spacing-y-96`
