import tw, { theme } from './macro'

// https://tailwindcss.com/docs/translate

tw`translate-x-0`
tw`translate-y-0`
tw`translate-x-px`
tw`translate-y-px`
tw`translate-x-0.5`
tw`translate-y-0.5`
tw`translate-x-1`
tw`translate-y-1`
tw`translate-x-1.5`
tw`translate-y-1.5`
tw`translate-x-2`
tw`translate-y-2`
tw`translate-x-2.5`
tw`translate-y-2.5`
tw`translate-x-3`
tw`translate-y-3`
tw`translate-x-3.5`
tw`translate-y-3.5`
tw`translate-x-4`
tw`translate-y-4`
tw`translate-x-5`
tw`translate-y-5`
tw`translate-x-6`
tw`translate-y-6`
tw`translate-x-7`
tw`translate-y-7`
tw`translate-x-8`
tw`translate-y-8`
tw`translate-x-9`
tw`translate-y-9`
tw`translate-x-10`
tw`translate-y-10`
tw`translate-x-11`
tw`translate-y-11`
tw`translate-x-12`
tw`translate-y-12`
tw`translate-x-14`
tw`translate-y-14`
tw`translate-x-16`
tw`translate-y-16`
tw`translate-x-20`
tw`translate-y-20`
tw`translate-x-24`
tw`translate-y-24`
tw`translate-x-28`
tw`translate-y-28`
tw`translate-x-32`
tw`translate-y-32`
tw`translate-x-36`
tw`translate-y-36`
tw`translate-x-40`
tw`translate-y-40`
tw`translate-x-44`
tw`translate-y-44`
tw`translate-x-48`
tw`translate-y-48`
tw`translate-x-52`
tw`translate-y-52`
tw`translate-x-56`
tw`translate-y-56`
tw`translate-x-60`
tw`translate-y-60`
tw`translate-x-64`
tw`translate-y-64`
tw`translate-x-72`
tw`translate-y-72`
tw`translate-x-80`
tw`translate-y-80`
tw`translate-x-96`
tw`translate-y-96`
tw`translate-x-1/2`
tw`translate-x-1/3`
tw`translate-x-2/3`
tw`translate-x-1/4`
tw`translate-x-2/4`
tw`translate-x-3/4`
tw`translate-x-full`
tw`translate-y-1/2`
tw`translate-y-1/3`
tw`translate-y-2/3`
tw`translate-y-1/4`
tw`translate-y-2/4`
tw`translate-y-3/4`
tw`translate-y-full`

tw`transform`
tw`transform-gpu`
tw`transform-cpu`
tw`transform-none`

tw`translate-x-10000`
tw`-translate-x-10000`
