import tw, { theme } from './macro'

// https://tailwindcss.com/docs/border-radius
theme`borderRadius.`

tw`rounded-none`
tw`rounded-sm`
tw`rounded`
tw`rounded-md`
tw`rounded-lg`
tw`rounded-xl`
tw`rounded-2xl`
tw`rounded-3xl`
tw`rounded-full`
tw`rounded-t-none`
tw`rounded-r-none`
tw`rounded-b-none`
tw`rounded-l-none`
tw`rounded-t-sm`
tw`rounded-r-sm`
tw`rounded-b-sm`
tw`rounded-l-sm`
tw`rounded-t`
tw`rounded-r`
tw`rounded-b`
tw`rounded-l`
tw`rounded-t-lg`
tw`rounded-r-lg`
tw`rounded-b-lg`
tw`rounded-l-lg`
tw`rounded-t-xl`
tw`rounded-r-xl`
tw`rounded-b-xl`
tw`rounded-l-xl`
tw`rounded-t-2xl`
tw`rounded-r-2xl`
tw`rounded-b-2xl`
tw`rounded-l-2xl`
tw`rounded-t-3xl`
tw`rounded-r-3xl`
tw`rounded-b-3xl`
tw`rounded-l-3xl`
tw`rounded-t-full`
tw`rounded-r-full`
tw`rounded-b-full`
tw`rounded-l-full`
tw`rounded-tl-none`
tw`rounded-tr-none`
tw`rounded-br-none`
tw`rounded-bl-none`
tw`rounded-tl-sm`
tw`rounded-tr-sm`
tw`rounded-br-sm`
tw`rounded-bl-sm`
tw`rounded-tl`
tw`rounded-tr`
tw`rounded-br`
tw`rounded-bl`
tw`rounded-tl-lg`
tw`rounded-tr-lg`
tw`rounded-br-lg`
tw`rounded-bl-lg`
tw`rounded-tl-xl`
tw`rounded-tr-xl`
tw`rounded-br-xl`
tw`rounded-bl-xl`
tw`rounded-tl-2xl`
tw`rounded-tr-2xl`
tw`rounded-br-2xl`
tw`rounded-bl-2xl`
tw`rounded-tl-3xl`
tw`rounded-tr-3xl`
tw`rounded-br-3xl`
tw`rounded-bl-3xl`
tw`rounded-tl-full`
tw`rounded-tr-full`
tw`rounded-br-full`
tw`rounded-bl-full`

tw`rounded-[12px]`
tw`rounded-t-[var(--radius)] rounded-r-[var(--radius)] rounded-b-[var(--radius)] rounded-l-[var(--radius)]`
tw`rounded-tr-[var(--radius)] rounded-br-[var(--radius)] rounded-bl-[var(--radius)] rounded-tl-[var(--radius)]`
