import tw from './macro'

// https://tailwindcss.com/docs/border-radius
tw`rounded-none`
tw`rounded-sm`
tw`rounded`
tw`rounded-md`
tw`rounded-lg`
tw`rounded-xl`
tw`rounded-2xl`
tw`rounded-3xl`
tw`rounded-full`
tw`rounded-t-none`
tw`rounded-r-none`
tw`rounded-b-none`
tw`rounded-l-none`
tw`rounded-t-sm`
tw`rounded-r-sm`
tw`rounded-b-sm`
tw`rounded-l-sm`
tw`rounded-t`
tw`rounded-r`
tw`rounded-b`
tw`rounded-l`
tw`rounded-t-lg`
tw`rounded-r-lg`
tw`rounded-b-lg`
tw`rounded-l-lg`
tw`rounded-t-xl`
tw`rounded-r-xl`
tw`rounded-b-xl`
tw`rounded-l-xl`
tw`rounded-t-2xl`
tw`rounded-r-2xl`
tw`rounded-b-2xl`
tw`rounded-l-2xl`
tw`rounded-t-3xl`
tw`rounded-r-3xl`
tw`rounded-b-3xl`
tw`rounded-l-3xl`
tw`rounded-t-full`
tw`rounded-r-full`
tw`rounded-b-full`
tw`rounded-l-full`
tw`rounded-tl-none`
tw`rounded-tr-none`
tw`rounded-br-none`
tw`rounded-bl-none`
tw`rounded-tl-sm`
tw`rounded-tr-sm`
tw`rounded-br-sm`
tw`rounded-bl-sm`
tw`rounded-tl`
tw`rounded-tr`
tw`rounded-br`
tw`rounded-bl`
tw`rounded-tl-lg`
tw`rounded-tr-lg`
tw`rounded-br-lg`
tw`rounded-bl-lg`
tw`rounded-tl-xl`
tw`rounded-tr-xl`
tw`rounded-br-xl`
tw`rounded-bl-xl`
tw`rounded-tl-2xl`
tw`rounded-tr-2xl`
tw`rounded-br-2xl`
tw`rounded-bl-2xl`
tw`rounded-tl-3xl`
tw`rounded-tr-3xl`
tw`rounded-br-3xl`
tw`rounded-bl-3xl`
tw`rounded-tl-full`
tw`rounded-tr-full`
tw`rounded-br-full`
tw`rounded-bl-full`

// https://tailwindcss.com/docs/border-width
tw`border`
tw`border-0`
tw`border-2`
tw`border-4`
tw`border-8`
tw`border-t`
tw`border-r`
tw`border-b`
tw`border-l`
tw`border-t-0`
tw`border-r-0`
tw`border-b-0`
tw`border-l-0`
tw`border-t-2`
tw`border-r-2`
tw`border-b-2`
tw`border-l-2`
tw`border-t-4`
tw`border-r-4`
tw`border-b-4`
tw`border-l-4`
tw`border-t-8`
tw`border-r-8`
tw`border-b-8`
tw`border-l-8`

// https://tailwindcss.com/docs/border-color
tw`border-transparent`
tw`border-current`
tw`border-black`
tw`border-white`
tw`border-gray-100`
tw`border-gray-200`
tw`border-gray-300`
tw`border-gray-400`
tw`border-gray-500`
tw`border-gray-600`
tw`border-gray-700`
tw`border-gray-800`
tw`border-gray-900`
tw`border-red-100`
tw`border-red-200`
tw`border-red-300`
tw`border-red-400`
tw`border-red-500`
tw`border-red-600`
tw`border-red-700`
tw`border-red-800`
tw`border-red-900`
tw`border-orange-100`
tw`border-orange-200`
tw`border-orange-300`
tw`border-orange-400`
tw`border-orange-500`
tw`border-orange-600`
tw`border-orange-700`
tw`border-orange-800`
tw`border-orange-900`
tw`border-yellow-100`
tw`border-yellow-200`
tw`border-yellow-300`
tw`border-yellow-400`
tw`border-yellow-500`
tw`border-yellow-600`
tw`border-yellow-700`
tw`border-yellow-800`
tw`border-yellow-900`
tw`border-green-100`
tw`border-green-200`
tw`border-green-300`
tw`border-green-400`
tw`border-green-500`
tw`border-green-600`
tw`border-green-700`
tw`border-green-800`
tw`border-green-900`
tw`border-teal-100`
tw`border-teal-200`
tw`border-teal-300`
tw`border-teal-400`
tw`border-teal-500`
tw`border-teal-600`
tw`border-teal-700`
tw`border-teal-800`
tw`border-teal-900`
tw`border-blue-100`
tw`border-blue-200`
tw`border-blue-300`
tw`border-blue-400`
tw`border-blue-500`
tw`border-blue-600`
tw`border-blue-700`
tw`border-blue-800`
tw`border-blue-900`
tw`border-indigo-100`
tw`border-indigo-200`
tw`border-indigo-300`
tw`border-indigo-400`
tw`border-indigo-500`
tw`border-indigo-600`
tw`border-indigo-700`
tw`border-indigo-800`
tw`border-indigo-900`
tw`border-purple-100`
tw`border-purple-200`
tw`border-purple-300`
tw`border-purple-400`
tw`border-purple-500`
tw`border-purple-600`
tw`border-purple-700`
tw`border-purple-800`
tw`border-purple-900`
tw`border-pink-100`
tw`border-pink-200`
tw`border-pink-300`
tw`border-pink-400`
tw`border-pink-500`
tw`border-pink-600`
tw`border-pink-700`
tw`border-pink-800`
tw`border-pink-900`

// https://tailwindcss.com/docs/border-opacity
tw`border-opacity-0`
tw`border-opacity-25`
tw`border-opacity-50`
tw`border-opacity-75`
tw`border-opacity-100`

// https://tailwindcss.com/docs/border-style
tw`border-solid`
tw`border-dashed`
tw`border-dotted`
tw`border-double`
tw`border-none`

// https://tailwindcss.com/docs/divide
tw`divide-x-0`
tw`divide-x-2`
tw`divide-x-4`
tw`divide-x-8`
tw`divide-x`
tw`divide-y-0`
tw`divide-y-2`
tw`divide-y-4`
tw`divide-y-8`
tw`divide-y`
tw`divide-x-reverse`
tw`divide-y-reverse`

// https://tailwindcss.com/docs/divide-color
tw`divide-transparent`
tw`divide-current`
tw`divide-black`
tw`divide-white`
tw`divide-gray-100`
tw`divide-gray-200`
tw`divide-gray-300`
tw`divide-gray-400`
tw`divide-gray-500`
tw`divide-gray-600`
tw`divide-gray-700`
tw`divide-gray-800`
tw`divide-gray-900`
tw`divide-red-100`
tw`divide-red-200`
tw`divide-red-300`
tw`divide-red-400`
tw`divide-red-500`
tw`divide-red-600`
tw`divide-red-700`
tw`divide-red-800`
tw`divide-red-900`
tw`divide-orange-100`
tw`divide-orange-200`
tw`divide-orange-300`
tw`divide-orange-400`
tw`divide-orange-500`
tw`divide-orange-600`
tw`divide-orange-700`
tw`divide-orange-800`
tw`divide-orange-900`
tw`divide-yellow-100`
tw`divide-yellow-200`
tw`divide-yellow-300`
tw`divide-yellow-400`
tw`divide-yellow-500`
tw`divide-yellow-600`
tw`divide-yellow-700`
tw`divide-yellow-800`
tw`divide-yellow-900`
tw`divide-green-100`
tw`divide-green-200`
tw`divide-green-300`
tw`divide-green-400`
tw`divide-green-500`
tw`divide-green-600`
tw`divide-green-700`
tw`divide-green-800`
tw`divide-green-900`
tw`divide-teal-100`
tw`divide-teal-200`
tw`divide-teal-300`
tw`divide-teal-400`
tw`divide-teal-500`
tw`divide-teal-600`
tw`divide-teal-700`
tw`divide-teal-800`
tw`divide-teal-900`
tw`divide-blue-100`
tw`divide-blue-200`
tw`divide-blue-300`
tw`divide-blue-400`
tw`divide-blue-500`
tw`divide-blue-600`
tw`divide-blue-700`
tw`divide-blue-800`
tw`divide-blue-900`
tw`divide-indigo-100`
tw`divide-indigo-200`
tw`divide-indigo-300`
tw`divide-indigo-400`
tw`divide-indigo-500`
tw`divide-indigo-600`
tw`divide-indigo-700`
tw`divide-indigo-800`
tw`divide-indigo-900`
tw`divide-purple-100`
tw`divide-purple-200`
tw`divide-purple-300`
tw`divide-purple-400`
tw`divide-purple-500`
tw`divide-purple-600`
tw`divide-purple-700`
tw`divide-purple-800`
tw`divide-purple-900`
tw`divide-pink-100`
tw`divide-pink-200`
tw`divide-pink-300`
tw`divide-pink-400`
tw`divide-pink-500`
tw`divide-pink-600`
tw`divide-pink-700`
tw`divide-pink-800`
tw`divide-pink-900`

tw`divide-solid`
tw`divide-dashed`
tw`divide-dotted`
tw`divide-double`
tw`divide-none`

// https://tailwindcss.com/docs/divide-opacity
tw`border-opacity-0`
tw`border-opacity-25`
tw`border-opacity-50`
tw`border-opacity-75`
tw`border-opacity-100`
