import tw from './macro'

// https://tailwindcss.com/docs/transform
tw`transform`
// tw`transform-gpu`
// tw`transform-none`

// https://tailwindcss.com/docs/transform-origin
tw`origin-center`
tw`origin-top`
tw`origin-top-right`
tw`origin-right`
tw`origin-bottom-right`
tw`origin-bottom`
tw`origin-bottom-left`
tw`origin-left`
tw`origin-top-left`

// https://tailwindcss.com/docs/scale
tw`scale-0`
tw`scale-50`
tw`scale-75`
tw`scale-90`
tw`scale-95`
tw`scale-100`
tw`scale-105`
tw`scale-110`
tw`scale-125`
tw`scale-150`
tw`scale-x-0`
tw`scale-x-50`
tw`scale-x-75`
tw`scale-x-90`
tw`scale-x-95`
tw`scale-x-100`
tw`scale-x-105`
tw`scale-x-110`
tw`scale-x-125`
tw`scale-x-150`
tw`scale-y-0`
tw`scale-y-50`
tw`scale-y-75`
tw`scale-y-90`
tw`scale-y-95`
tw`scale-y-100`
tw`scale-y-105`
tw`scale-y-110`
tw`scale-y-125`
tw`scale-y-150`

// https://tailwindcss.com/docs/rotate
tw`rotate-0`
tw`rotate-1`
tw`rotate-2`
tw`rotate-3`
tw`rotate-6`
tw`rotate-12`
tw`rotate-45`
tw`rotate-90`
tw`rotate-180`
tw`-rotate-1`
tw`-rotate-2`
tw`-rotate-3`
tw`-rotate-6`
tw`-rotate-12`
tw`-rotate-45`
tw`-rotate-90`
tw`-rotate-180`

// https://tailwindcss.com/docs/translate
tw`translate-x-0`
tw`translate-x-0.5`
tw`translate-x-1`
tw`translate-x-1.5`
tw`translate-x-2`
tw`translate-x-2.5`
tw`translate-x-3`
tw`translate-x-3.5`
tw`translate-x-4`
tw`translate-x-5`
tw`translate-x-6`
tw`translate-x-7`
tw`translate-x-8`
tw`translate-x-9`
tw`translate-x-10`
tw`translate-x-11`
tw`translate-x-12`
tw`translate-x-14`
tw`translate-x-16`
tw`translate-x-20`
tw`translate-x-24`
tw`translate-x-28`
tw`translate-x-32`
tw`translate-x-36`
tw`translate-x-40`
tw`translate-x-44`
tw`translate-x-48`
tw`translate-x-52`
tw`translate-x-56`
tw`translate-x-60`
tw`translate-x-64`
tw`translate-x-72`
tw`translate-x-80`
tw`translate-x-96`
tw`translate-x-px`
tw`translate-x-1/2`
tw`translate-x-1/3`
tw`translate-x-2/3`
tw`translate-x-1/4`
tw`translate-x-2/4`
tw`translate-x-3/4`
tw`translate-x-full`
tw`-translate-x-0`
tw`-translate-x-0.5`
tw`-translate-x-1`
tw`-translate-x-1.5`
tw`-translate-x-2`
tw`-translate-x-2.5`
tw`-translate-x-3`
tw`-translate-x-3.5`
tw`-translate-x-4`
tw`-translate-x-5`
tw`-translate-x-6`
tw`-translate-x-7`
tw`-translate-x-8`
tw`-translate-x-9`
tw`-translate-x-10`
tw`-translate-x-11`
tw`-translate-x-12`
tw`-translate-x-14`
tw`-translate-x-16`
tw`-translate-x-20`
tw`-translate-x-24`
tw`-translate-x-28`
tw`-translate-x-32`
tw`-translate-x-36`
tw`-translate-x-40`
tw`-translate-x-44`
tw`-translate-x-48`
tw`-translate-x-52`
tw`-translate-x-56`
tw`-translate-x-60`
tw`-translate-x-64`
tw`-translate-x-72`
tw`-translate-x-80`
tw`-translate-x-96`
tw`-translate-x-px`
tw`-translate-x-1/2`
tw`-translate-x-1/3`
tw`-translate-x-2/3`
tw`-translate-x-1/4`
tw`-translate-x-2/4`
tw`-translate-x-3/4`
tw`-translate-x-full`
tw`translate-y-0`
tw`translate-y-0.5`
tw`translate-y-1`
tw`translate-y-1.5`
tw`translate-y-2`
tw`translate-y-2.5`
tw`translate-y-3`
tw`translate-y-3.5`
tw`translate-y-4`
tw`translate-y-5`
tw`translate-y-6`
tw`translate-y-7`
tw`translate-y-8`
tw`translate-y-9`
tw`translate-y-10`
tw`translate-y-11`
tw`translate-y-12`
tw`translate-y-14`
tw`translate-y-16`
tw`translate-y-20`
tw`translate-y-24`
tw`translate-y-28`
tw`translate-y-32`
tw`translate-y-36`
tw`translate-y-40`
tw`translate-y-44`
tw`translate-y-48`
tw`translate-y-52`
tw`translate-y-56`
tw`translate-y-60`
tw`translate-y-64`
tw`translate-y-72`
tw`translate-y-80`
tw`translate-y-96`
tw`translate-y-px`
tw`translate-y-1/2`
tw`translate-y-1/3`
tw`translate-y-2/3`
tw`translate-y-1/4`
tw`translate-y-2/4`
tw`translate-y-3/4`
tw`translate-y-full`
tw`-translate-y-0`
tw`-translate-y-0.5`
tw`-translate-y-1`
tw`-translate-y-1.5`
tw`-translate-y-2`
tw`-translate-y-2.5`
tw`-translate-y-3`
tw`-translate-y-3.5`
tw`-translate-y-4`
tw`-translate-y-5`
tw`-translate-y-6`
tw`-translate-y-7`
tw`-translate-y-8`
tw`-translate-y-9`
tw`-translate-y-10`
tw`-translate-y-11`
tw`-translate-y-12`
tw`-translate-y-14`
tw`-translate-y-16`
tw`-translate-y-20`
tw`-translate-y-24`
tw`-translate-y-28`
tw`-translate-y-32`
tw`-translate-y-36`
tw`-translate-y-40`
tw`-translate-y-44`
tw`-translate-y-48`
tw`-translate-y-52`
tw`-translate-y-56`
tw`-translate-y-60`
tw`-translate-y-64`
tw`-translate-y-72`
tw`-translate-y-80`
tw`-translate-y-96`
tw`-translate-y-px`
tw`-translate-y-1/2`
tw`-translate-y-1/3`
tw`-translate-y-2/3`
tw`-translate-y-1/4`
tw`-translate-y-2/4`
tw`-translate-y-3/4`
tw`-translate-y-full`

// https://tailwindcss.com/docs/skew
tw`skew-x-0`
tw`skew-x-1`
tw`skew-x-2`
tw`skew-x-3`
tw`skew-x-6`
tw`skew-x-12`
tw`-skew-x-12`
tw`-skew-x-6`
tw`-skew-x-3`
tw`-skew-x-2`
tw`-skew-x-1`
tw`skew-y-0`
tw`skew-y-1`
tw`skew-y-2`
tw`skew-y-3`
tw`skew-y-6`
tw`skew-y-12`
tw`-skew-y-12`
tw`-skew-y-6`
tw`-skew-y-3`
tw`-skew-y-2`
tw`-skew-y-1`
